### PR TITLE
Print help when no arguments are passed

### LINKED ISSUE #24: help should be shown if no arguments are provided
```sh
$ helm
The Kubernetes package manager

Common actions for Helm:

- helm search:    search for charts
- helm pull:      download a chart to your local directory to view
- helm install:   upload the chart to Kubernetes
- helm list:      list releases of charts
...
```

Actual results:
```sh
$ helm mapkubeapis
Error: name of release to be mapped needs to be passed
Error: plugin "mapkubeapis" exited with error
```

Expected results:
```sh
$ helm mapkubeapis
Map release deprecated or removed Kubernetes APIs in-place

Usage:
  mapkubeapis [flags] RELEASE

Flags:
      --dry-run                  simulate a command
  -h, --help                     help for mapkubeapis
      --kube-context string      name of the kubeconfig context to use
      --kubeconfig string        path to the kubeconfig file
      --mapfile string           path to the API mapping file (default "~/helm/plugins/helm-mapkubeapis/config/Map.yaml")
      --namespace string         namespace scope of the release. For Helm v2, this is the Tiller namespace e.g. kube-system
  -s, --release-storage string   for Helm v2 only - release storage type/object. It can be 'secrets' or 'configmaps'. This is only used with the 'tiller-out-cluster' flag (default "secrets")
      --tiller-out-cluster       for Helm v2 only - when Tiller is not running in the cluster e.g. Tillerless
      --v2                       run for Helm v2 release. The default is Helm v3.
```

### PR DESCRIPTION
**Pull request by flowjo-shaunr**
This fixes #24 and also prints an error when more than one argument is passed to maintain the original behavior.

### CODE REVIEW

File: cmd/mapkubeapis/map.go [hunk 1]
```diff
@@ -52,8 +52,11 @@ func newMapCmd(out io.Writer, args []string) *cobra.Command {
 		Long:         "Map release deprecated or removed Kubernetes APIs in-place",
 		SilenceUsage: true,
 		Args: func(cmd *cobra.Command, args []string) error {
-			if len(args) != 1 {
-				return errors.New("name of release to be mapped needs to be passed")
+			if len(args) == 0 {
+				cmd.Help()
+				os.Exit(0)
+			} else if len(args) > 1 {
+				return errors.New("Only one release name may be passed at a time")
```
Comment (hickeyma) [inline cmd/mapkubeapis/map.go:59]: Nit: using lower case format for messages:

Only --> only

Comment (flowjo-shaunr) [reply cmd/mapkubeapis/map.go]: Got it. Fixed in the next commit

File: cmd/mapkubeapis/map.go [hunk 2]
```diff
@@ -52,8 +52,11 @@ func newMapCmd(out io.Writer, args []string) *cobra.Command {
 		Long:         "Map release deprecated or removed Kubernetes APIs in-place",
 		SilenceUsage: true,
 		Args: func(cmd *cobra.Command, args []string) error {
-			if len(args) != 1 {
-				return errors.New("name of release to be mapped needs to be passed")
+			if len(args) == 0 {
+				cmd.Help()
+				os.Exit(0)
```
Comment (hickeyma) [inline cmd/mapkubeapis/map.go:57]: Sorry missed this but should this be `os.Exit(1)` ?

Comment (flowjo-shaunr) [reply cmd/mapkubeapis/map.go:57]: Yeah, no problem. I wasn't really sure what the standard was since looking at different tools, it was inconsistent on whether printing the help on no args was an error state or not

File: cmd/mapkubeapis/map.go [hunk 3]
```diff
@@ -52,8 +52,11 @@ func newMapCmd(out io.Writer, args []string) *cobra.Command {
 		Long:         "Map release deprecated or removed Kubernetes APIs in-place",
 		SilenceUsage: true,
 		Args: func(cmd *cobra.Command, args []string) error {
-			if len(args) != 1 {
-				return errors.New("name of release to be mapped needs to be passed")
+			if len(args) == 0 {
+				cmd.Help()
+				os.Exit(1)
```
Comment (jsoref) [inline cmd/mapkubeapis/map.go:57]: The exit code for this should be `0`.

Comment (hickeyma) [reply cmd/mapkubeapis/map.go:57]: @jsoref Usually 0 is a success. This is an error and should the exit value 1 then?

Comment (jsoref) [reply cmd/mapkubeapis/map.go:57]: Running a command with no arguments and getting help isn't an error.

```sh
$ cmd=helm; out=$(mktemp); err=$(mktemp); $cmd > $out 2> $err; echo $? $(cat $out | wc -l) $(cat $err | wc -l); rm $out $err
0 94 0
$ cmd=kubectl; out=$(mktemp); err=$(mktemp); $cmd > $out 2> $err; echo $? $(cat $out | wc -l) $(cat $err | wc -l); rm $out $err
0 66 0
$ cmd=docker; out=$(mktemp); err=$(mktemp); $cmd > $out 2> $err; echo $? $(cat $out | wc -l) $(cat $err | wc -l); rm $out $err
0 0 78
$ cmd=false; out=$(mktemp); err=$(mktemp); $cmd > $out 2> $err; echo $? $(cat $out | wc -l) $(cat $err | wc -l); rm $out $err
1 0 0
```

Comment (flowjo-shaunr) [reply cmd/mapkubeapis/map.go:57]: Some commands do return error when run with no arguments, for instance `git`. I think since providing more than one argument is also an error, it makes sense for none to be an error as well.

Comment (hickeyma) [reply cmd/mapkubeapis/map.go:57]: I am now having doubts that we should be showing the usage. Looking again @jsoref issue raised in #24, running just `helm` was used as an example. This should show usage as no command is used. However, in the plugin case, the command is given but the mandatory arg of release is not. This to me this is an error and usage should not be shown. What do you think @flowjo-shaunr  @jsoref ?

Comment (jsoref) [reply cmd/mapkubeapis/map.go:57]: The main way to learn how to use a thing is via usage. When I run top level commands without arguments, they suggest how to use them, including subcommands. When I run those subcommands without arguments, they suggest how to use them.

I can provide examples...

Comment (hickeyma) [reply cmd/mapkubeapis/map.go:57]: Should this be the sole job of the `--help` flag?

Comment (flowjo-shaunr) [reply cmd/mapkubeapis/map.go:57]: I think it's still okay to be printing full usage, even as a subcommand (plugin), since it is a separate tool that doesn't necessarily inherit any of the root behaviors of the `helm` command, such as any global flags. That could be the sole job of the `--help` flag, but personally I feel that it's more convenient as a user to just receive the full usage of the plugin if I run nothing, rather than receiving a message that tells me to then run `--help`

Comment (hickeyma) [reply cmd/mapkubeapis/map.go:57]: Thanks for the great feedback @jsoref @flowjo-shaunr. Taking this on board, let's keep the output of usage when just the command run and the error code of 1 because it is essentially an error as the mandatory arg is not passed.

Hope this is ok to all.

**Comment by m4ver1k** [comment]
@hickeyma I was about to raise an issue on this, but stumbled up on this conversation, while digging around to understand why this change was done.
